ny_taxi_dbt:
  outputs:
    dev:
      dataset: dbt_data
      job_execution_timeout_seconds: 60
      job_retries: 1
      keyfile: /root/.google/credentials/ny-rides-nate.json
      location: US
      method: service-account
      priority: interactive
      project: ny-rides-nate
      threads: 4
      type: bigquery
  target: dev
